
export const MOTIVATIONAL_QUOTES = [
    "Believe you can and you're halfway there.",
    "The journey of a thousand miles begins with a single step.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Don't watch the clock; do what it does. Keep going.",
    "The secret of getting ahead is getting started.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Every day is a new chance to change your life.",
    "One day at a time.",
    "You are stronger than your cravings.",
    "The temptation you feel now is temporary. The pride you'll feel later is forever.",
    "Fall seven times, stand up eight.",
    "You didn't come this far to only come this far.",
    "A year from now, you will wish you had started today.",
    "Your health is an investment, not an expense.",
    "Breathe in courage, breathe out fear.",
    "Small progress is still progress.",
    "Be proud of how far you've come. Have faith in how far you can go.",
    "The future you is thanking you right now.",
    "Choose what you want most over what you want now.",
    "Your lungs are healing with every breath you take.",
    "Every cigarette not smoked is a victory.",
    "You are rewriting your story.",
    "Don't let a slip become a fall.",
    "The best time to quit was yesterday. The next best time is now.",
    "Your body is a temple, not an ashtray.",
    "Freedom from smoking is a beautiful thing.",
    "This is your comeback story.",
    "Cravings last for minutes. Regret lasts much longer.",
    "Stay positive. Work hard. Make it happen.",
    "You've got this. I believe in you.",
    "Your determination is inspiring.",
    "Think of all the money you're saving!",
    "Your senses of taste and smell are returning.",
    "You are choosing a longer, healthier life.",
    "The first few days are the hardest. You're past that.",
    "Your hard work is paying off.",
    "Keep your eyes on the prize: a healthier you.",
    "Replace old habits with new, healthy ones.",
    "You are a non-smoker now.",
    "With every passing day, it gets easier.",
    "Look how far you've come!",
    "Your breath is fresher, and so is your outlook.",
    "Never doubt your strength.",
    "This is one of the best decisions you'll ever make.",
    "Your willpower is a muscle. The more you use it, the stronger it gets.",
    "You are in control.",
    "Each day smoke-free is a gift to yourself.",
    "The craving is a sign that your body is healing.",
    "You are reclaiming your health.",
    "Your future self will be so proud.",
    "Don't trade your progress for a moment of weakness.",
    "The desire to smoke will fade. Your strength will not."
];
